### ISSUE TITLE
rename repo to planetmint-driver-python

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-driver-python#2]
### Description

we want to rename the repo in such a way that we have one pattern on how we name bindings for the different languages.
The driver needs to be renamed planetmint-python. 

**DOs**
Please rename 
* the repo and 
* the package that is deployed/released. (we decided that this Is not needed).
* rename the references on planetmint itself so that the proper packages are referenced and used.
* 

**DON'T**
* rename the python module itself. I don#t think that we need this

**Comment by Sangatdas** [comment]
I don't have access privileges to do this I believe
