### ISSUE TITLE
Event listeners on the roadmap?

### ISSUE THREAD

**Issue by PoCk3T** [planetmint/planetmint-driver-python#69]
### Description

Hi Planetmint team, great job on this project, I love it! I was wondering if the Python driver is capable of listening to new transactions committed to a Planetmint network, so that my own application logic can get triggered and act upon any new transactions? 

 

### What I Did

I've looked in the docs and in the existing refinement proposals, but didn't find any related feature 

EDIT: an event listener on any new block committed to the Planetmint database would also do the work, provided that the listener will have access to the content ( list of transactions ) committed within a given block

**Comment by eckelj** [comment]
@PoCk3T thank you for reaching out. the block event contains the list of all the transaction ids within the block:

https://github.com/planetmint/planetmint/blob/4472a1a3ee8ea166dd911986136c73d547eea511/tests/web/test_websocket_server.py#L68-L72

the ws event for the transactions contains the block heights and the trasnaction id per transactions as a list:

https://github.com/planetmint/planetmint/blob/4472a1a3ee8ea166dd911986136c73d547eea511/tests/web/test_websocket_server.py#L42-L45
