### ISSUE TITLE
SonarQube 

### ISSUE THREAD

**Issue by GR3G0RYO** [planetmint/planetmint-driver-python#87]

**Comment by jmastr** [comment]
ArgoCD: https://argocd-prod.r3c.network/applications/argo-cd/rddl-sonarqube
URL: https://sonarqube.rddl.io/

Use LDAP to login

**Comment by jmastr** [comment]
![sonarqube.rddl.io_dashboard.png](https://images.zenhubusercontent.com/62a0603cc6b72e70c4a71cad/3a62ad02-aa7c-4fda-8cc0-68080f91cbfb)
