### ISSUE TITLE
 Testnet validator ordering and initial setup at our workshop

### ISSUE THREAD

**Issue by GR3G0RYO** [planetmint/planetmint-driver-python#88]
The TAs need to be provisioned after they get attached to the validators.

**Comment by jmastr** [comment]
Seven validators are ordered and being delivered:

**Comment by eckelj** [comment]
@jmastr, should we rename the title of the document? IThe intention of the ticket was to set up the nodes. Not the provisioning process itself.
What do you think about this?

**Comment by nmarcovici** [comment]
All seven validators have Ubuntu 22.04 installed. Due to missing power cables the validators are not running.

**Comment by jmastr** [comment]
@nmarcovici do we need to buy new ones? can maybe Maurice help?

**Comment by GR3G0RYO** [comment]
Were the NUC's we ordered suppose to come with power cables? Lets clarify
that first.

**Comment by nmarcovici** [comment]
@jmastr already discussed with Maurice, the cables will arrive next week.

**Comment by jmastr** [comment]
@nmarcovici the title on Amazon includes „EUCord“ and one comment mentions: „This is actually a barebones machine with an EU power plug.“

**Comment by nmarcovici** [comment]
@GR3G0RYO the NUC`s came with power supply but not with the cable that goes from the power supply to the plug in, I don`t know why or how come but this is how it came.

**Comment by jmastr** [comment]
„this is an Intel NUC, arrived with a European 2 pin plug“

**Comment by jmastr** [comment]
@nmarcovici to our last comment: that’s how it should be. NUCs are supposed to be put together. That’s why we needed to order SSDs and RAMs separately. 

Please buy those seven cables somewhere. Can’t be expensive. Let Maurice help if necessary.

**Comment by nmarcovici** [comment]
@jmastr after discussing with Maurice, the best option was to get this cables from amazon as from a different store where expensive (12euros per cable) so he ordered the cables from amazons and they will come on Monday(5euros per cable)

**Comment by nmarcovici** [comment]
@jmastr @GR3G0RYO 3 nodes are up, the ip where forwarded and it`s on Jurgen side now to connect and configure them as it`s needed, Sadly Maurice and I could`t find more power cables so the other 4 nodes will be available from next week.

**Comment by nmarcovici** [comment]
@jmastr @GR3G0RYO 3 nodes are up, the ip where forwarded and it`s on Jurgen side now to connect and configure them as it`s needed, Sadly Maurice and I could`t find more power cables so the other 4 nodes will be available from next week.

**Comment by nmarcovici** [comment]
correction no the ip the ports where forwarded*
